In [1]:
import pandas as pd

data = pd.read_csv("C:\\Users\\kesha\\Desktop\\My Documents\\dataset.csv")

In [2]:
X = data.drop("target", axis=1)
y = data["target"]


In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [4]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [5]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.8821034775233249
Classification Report:
              precision    recall  f1-score   support

         Bus       0.79      0.93      0.85       189
         Car       0.86      0.78      0.82       243
       Still       0.93      0.94      0.94       248
       Train       0.86      0.83      0.85       243
     Walking       0.94      0.94      0.94       256

    accuracy                           0.88      1179
   macro avg       0.88      0.88      0.88      1179
weighted avg       0.88      0.88      0.88      1179

Confusion Matrix:
[[175   5   0   5   4]
 [ 26 189   8  17   3]
 [  2   3 234   7   2]
 [  9  19   8 202   5]
 [  9   3   1   3 240]]


In [16]:
# Replace the 'new_sensor_readings' variable with your actual sensor readings
new_sensor_readings = [[17,	9.728209279	,9.111534979	,10.15468033,	0.210600143	,0,	0	,0,	0,	0,	0	,0	,0

]]

prediction = model.predict(new_sensor_readings)
print("Predicted Target:", prediction)


Predicted Target: ['Train']


c:\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

def predict_transport_mode(file_path):
    # Load the data
    data = pd.read_csv(file_path)

    # Define the feature columns
    features = ['android.sensor.accelerometer#mean', 
                'android.sensor.accelerometer#min', 
                'android.sensor.accelerometer#max', 
                'android.sensor.gyroscope#mean', 
                'android.sensor.gyroscope#min', 
                'android.sensor.gyroscope#max']

    # Define the target column
    target = ['target']

    # Encode the target column
    le = LabelEncoder()
    data['target'] = le.fit_transform(data['target'])

    # Split the data into a training set and a test set
    X_train, X_test, y_train, y_test = train_test_split(data[features], data[target], test_size=0.2, random_state=42)

    # Initialize and fit the Random Forest classifier
    rf = RandomForestClassifier(random_state=42)
    rf.fit(X_train, y_train.values.ravel())

    # Prompt the user to enter their own sensor readings
    accelerometer_mean = float(input("Enter the mean accelerometer reading: "))
    accelerometer_min = float(input("Enter the min accelerometer reading: "))
    accelerometer_max = float(input("Enter the max accelerometer reading: "))
    gyroscope_mean = float(input("Enter the mean gyroscope reading: "))
    gyroscope_min = float(input("Enter the min gyroscope reading: "))
    gyroscope_max = float(input("Enter the max gyroscope reading: "))

    # Create a DataFrame from the user's input
    user_input = pd.DataFrame([[accelerometer_mean, accelerometer_min, accelerometer_max, gyroscope_mean, gyroscope_min, gyroscope_max]], columns=features)

    # Use the trained model to predict the mode of transportation
    prediction = rf.predict(user_input)

    # Decode the prediction
    prediction = le.inverse_transform(prediction)

    # Print the predicted mode of transportation
    print("The predicted mode of transportation is: " + prediction[0])

# Use the function
predict_transport_mode('C:\\Users\\kesha\\Desktop\\My Documents\\dataset.csv')


The predicted mode of transportation is: Bus


In [12]:
import pandas as pd
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score

# Initialize the SGDClassifier
sgd_clf = SGDClassifier(loss='log', random_state=42)

# Initialize a StandardScaler
scaler = StandardScaler()

# Initialize a LabelEncoder
le = LabelEncoder()

# We'll read the data in chunks, preprocess each chunk, and train the model
chunksize = 10 ** 5
i = 0
for chunk in pd.read_csv(r'C:\Users\kesha\Downloads\cleaned.csv\cleaned.csv', chunksize=chunksize):
    print(f'Processing chunk {i}')
    i += 1
    
    # Sample a fraction of the data to manage memory
    chunk_sample = chunk.sample(frac=0.05, random_state=42)

    # Extract features and target
    features_chunk = chunk_sample[['x', 'y', 'z']]
    target_chunk = chunk_sample['class']
    
    # If this is the first chunk, fit the LabelEncoder, otherwise, transform only
    if i == 1:
        target_chunk = le.fit_transform(target_chunk)
    else:
        target_chunk = le.transform(target_chunk)
    
    # Scale the features
    features_chunk = scaler.fit_transform(features_chunk)
    
    # Train the SGDClassifier
    sgd_clf.partial_fit(features_chunk, target_chunk, classes=np.unique(target_chunk))

# Check the performance of the model on the last chunk of data
y_pred_chunk = sgd_clf.predict(features_chunk)
accuracy = accuracy_score(target_chunk, y_pred_chunk)

print(f'Accuracy: {accuracy}')



Processing chunk 0


InvalidParameterError: The 'loss' parameter of SGDClassifier must be a str among {'modified_huber', 'perceptron', 'squared_error', 'hinge', 'epsilon_insensitive', 'squared_epsilon_insensitive', 'huber', 'log_loss', 'squared_hinge'}. Got 'log' instead.

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score

# Load the dataset
data = pd.read_csv(r'C:\Users\kesha\Downloads\reduced_cleaned.csv')

# Prepare the features and the target variable
X = data[['x', 'y', 'z']]
y = data['class']

# Encode the target variable
le = LabelEncoder()
y = le.fit_transform(y)

# Split the data into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize the feature variables
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize the RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)

print(f'Accuracy: {accuracy}')


MemoryError: Unable to allocate 34.5 MiB for an array with shape (4522442,) and data type float64